name: flutter_zoom_call
description: flutter video calling app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  firebase_remote_config: ^2.0.12

  #sign in
  google_sign_in: ^5.4.0


  #state management
  flutter_bloc: ^8.0.1
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0

  #error handling
  dartz: ^0.10.1

  #dependency injection
  get_it: ^7.2.0

  #date time format
  intl: ^0.17.0


  #for video calling
  jitsi_meet: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: 2.2.0
  flutter_launcher_icons: ^0.9.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/video_call_logo.png"


flutter:

  uses-material-design: true


  assets:
    - assets/img/onboarding.jpg
    - assets/img/video_call_logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
